import { readFile, stat } from 'fs/promises';
import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const CSV_PATH =
  process.env.POWERBI_CSV_PATH || '/Users/adrian/Code/bruss-cron/data/powerbi-dmcheck.csv';

export async function GET() {
  try {
    const csv = await readFile(CSV_PATH, 'utf-8');
    const stats = await stat(CSV_PATH);

    return new NextResponse(csv, {
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': 'attachment; filename="defects-data.csv"',
        'X-Generated-At': stats.mtime.toISOString(),
      },
    });
  } catch (error) {
    console.error('api/dmcheck-data/powerbi: CSV file not found -', CSV_PATH);
    return NextResponse.json(
      { error: 'CSV file not available. It will be generated by cron job.' },
      { status: 503 }
    );
  }
}
